### ISSUE TITLE
Very slow

### ISSUE THREAD

**Issue by benjaminmal** [rinchsan/renovate-config-validator#204]
This is a great tools but it is very slow. In my CI, it generally takes 1min or more to validate a 1 line file (extending a renovate template repository). Do you know how to speed up the validation? Thanks

**Comment by rinchsan** [comment]
This action just runs `renovate-config-validator`, which is an official cli tool from renovate, downloaded and installed via npx.
It is slightly hard to speed up this action because the execution speed really depends on npx download speed and execution speed of the cli tool.
Any ideas?

**Comment by benjaminmal** [comment]
Maybe some sort of catching? If the files haven't changed, then pass the validation. But maybe it's better to create an issue for the renovate package indeed.
