### ISSUE TITLE
Upgrade to node20?

### ISSUE THREAD

**Issue by hkroger** [rinchsan/renovate-config-validator#305]
I get error like this when using this action:

Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: rinchsan/renovate-config-validator@v0.0.12. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

It would be probably an easy fix.

CC: @rinchsan

**Comment by rinchsan** [comment]
@hkroger Thank you so much for reporting the issue!
I'm working on this at https://github.com/rinchsan/renovate-config-validator/pull/306

**Comment by rinchsan** [comment]
fixed in https://github.com/rinchsan/renovate-config-validator/releases/tag/v0.1.0
